# Cowsay example

name: Cow example

on:
  push:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: pip install cowsay
    - name: cowsay​
      run: cowsay -c cheese -t  'hey there'
  cowpy:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: pip install cowpy
    - name: cowpy
      run: cowpy -c tux hi there
  cowpy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install cowpy
      run: |
        pip install cowpy
    - name: run cowpy 
      run: |
        cowpy -c tux "hola mundo"
        echo "hola mundo" | cowpy -c tux
    - name: run script with examples
      run: |
        python bin/examples.py
