# Cowsay example

name: Cow example

on:
  push:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: pip install cowsay
    - name: cowsay​
      run: cowsay -c cheese -t  'hey there'
  cowpy:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: pip install cowpy
    - name: cowpy
      run: cowpy -c tux hi there
  call_file:
    runs-on: ubuntu-latest
    steps:
    - name: run examples
      run: python bin/examples.py
