# Cowsay example

name: Cow example

on:
  push:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: pip install cowsay
    - name: cowsay​
      run: cowsay -c cheese -t  'hey there'
