# Hello World example for DTU biosustain and DTU bioengineering Data Club

name: Cow example

on:
  push:

jobs:
  install_step:
    runs-on: ubuntu-latest
    steps:
    - name: pip install cowsay
      run: pip install cowsay
  use_step:
    runs-on: ubuntu-latest
    steps:
    - name: cowsay -c cheese -t  'hey there’​
      run: cowsay -c cheese -t  'hey there’​
